services:
  rag-app:
    build: .  # dice di creare l'immagine in base al Dockerfile nella cartella corrente
    container_name: rag-app
    ports:
      - "8501:8501"
    volumes:
      - ./uploaded_pdfs:/app/uploaded_pdfs
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      # Point to Docker OLLAMA service
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      # Point to Docker QDRANT service
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
    restart: unless-stopped


  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-server
    ports:
      - "6333:6333"
      - "6334:6334" # gRPC port, optional if you need it
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
    driver: local
